Update Package.swift
The manifest as is is invalid in Swift 6 language mode due to a concurrency error.

```
/Users/sas/Downloads/swift-html-to-pdf/Package.swift:11:16: error: static property 'htmlToPdf' is not concurrency-safe because non-'Sendable' type 'Target.Dependency' may have shared mutable state
 9 |
10 | extension Target.Dependency {
11 |     static let htmlToPdf: Self = .target(name: .htmlToPdf)
   |                `- error: static property 'htmlToPdf' is not concurrency-safe because non-'Sendable' type 'Target.Dependency' may have shared mutable state
12 | }
13 |
```